In [1]:
pip install rake-nltk

Collecting rake-nltk
  Downloading rake_nltk-1.0.6-py3-none-any.whl (9.1 kB)
Requirement already satisfied: nltk<4.0.0,>=3.6.2 in /usr/local/lib/python3.10/dist-packages (from rake-nltk) (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk<4.0.0,>=3.6.2->rake-nltk) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk<4.0.0,>=3.6.2->rake-nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk<4.0.0,>=3.6.2->rake-nltk) (2023.12.25)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk<4.0.0,>=3.6.2->rake-nltk) (4.66.2)
Installing collected packages: rake-nltk
Successfully installed rake-nltk-1.0.6

In [2]:
import pandas as pd
import numpy as np
from rake_nltk import Rake

**Top 43 IMDB Dataset**

In [3]:
films = pd.read_csv('/content/Films1.csv')

In [4]:
films

,Film Title,IMDb Rating,Letterboxd Rating,Director,Lead Cast,Year of Release,Genre,Plot,Runtime
0,The Shawshank Redemption,9.3,4.5,Frank Darabont,Tim Robbins Morgan Freeman Bob Gunton,1994,Drama,Two imprisoned men bond over a number of years...,142
1,The Godfather,9.2,4.4,Francis Ford Coppola,Marlon Brando Al Pacino James Caan,1972,Crime,The aging patriarch of an organized crime dyna...,175
2,The Godfather: Part II,9.0,4.4,Francis Ford Coppola,Al Pacino Robert De Niro Robert Duvall,1974,Crime,The early life and career of Vito Corleone in ...,202
3,The Dark Knight,9.0,4.5,Christopher Nolan,Christian Bale Heath Ledger Aaron Eckhart,2008,Action,When the menace known as The Joker wreaks havo...,152
4,12 Angry Men,9.0,4.4,Sidney Lumet,Henry Fonda Lee J. Cobb Martin Balsam,1957,Drama,A jury holdout attempts to prevent a miscarria...,96
5,Schindler's List,8.9,4.4,Steven Spielberg,Liam Neeson Ralph Fiennes Ben Kingsley,1993,Biography,"In German-occupied Poland during World War II,...",195
6,The Lord of the Rings: The Return of the King,8.9,4.5,Peter Jackson,Elijah Wood Viggo Mortensen Ian McKellen,2003,Adventure,Gandalf and Aragorn lead the World of Men agai...,201
7,Pulp Fiction,8.9,4.4,Quentin Tarantino,John Travolta Uma Thurman Samuel L. Jackson,1994,Crime,"The lives of two mob hitmen, a boxer, a gangst...",154
8,Forrest Gump,8.8,4.3,Robert Zemeckis,Tom Hanks Robin Wright Gary Sinise,1994,Drama,"The presidencies of Kennedy and Johnson, the V...",142
9,The Lord of the Rings: The Fellowship of the Ring,8.8,4.4,Peter Jackson,Elijah Wood Ian McKellen Orlando Bloom,2001,Adventure,A meek Hobbit from the Shire and eight compani...,178
10,Fight Club,8.8,4.4,David Fincher,Brad Pitt Edward Norton Meat Loaf,1999,Drama,An insomniac office worker and a devil-may-car...,139
11,The Lord of the Rings: The Two Towers,8.7,4.4,Peter Jackson,Elijah Wood Ian McKellen Viggo Mortensen,2002,Adventure,While Frodo and Sam edge closer to Mordor with...,179
12,Goodfellas,8.7,4.4,Martin Scorsese,Robert De Niro Ray Liotta Joe Pesci,1990,Biography,The story of Henry Hill and his life in the mo...,146
13,The Matrix,8.7,4.3,Lana Wachowski Lilly Wachowski Keanu Reeves La...,Lana Wachowski Lilly Wachowski Keanu Reeves La...,1999,Action,A computer hacker learns from mysterious rebel...,136
14,The Intouchables,8.5,4.2,Olivier Nakache Ã‰ric Toledano,FranÃ§ois Cluzet Omar Sy Anne Le Ny,2011,Biography,After he becomes a quadriplegic from a paragli...,112
15,The Lion King,8.5,4.2,Roger Allers Rob Minkoff,Matthew Broderick Jeremy Irons James Earl Jones,1994,Animation,Lion prince Simba and his father are targeted ...,88
16,Terminator 2: Judgment Day,8.5,4.2,James Cameron,Arnold Schwarzenegger Linda Hamilton Edward Fu...,1991,Action,"A cyborg, identical to the one who failed to k...",137
17,Back to the Future,8.5,4.3,Robert Zemeckis,Michael J. Fox Christopher Lloyd Lea Thompson,1985,Adventure,"Marty McFly, a 17-year-old high school student...",116
18,The Prestige,8.5,4.3,Christopher Nolan,Christian Bale Hugh Jackman Scarlett Johansson,2006,Drama,"After a tragic accident, two stage magicians e...",130
19,The Lives of Others,8.4,4.4,Florian Henckel von Donnersmarck,Ulrich MÃ¼he Martina Gedeck Sebastian Koch,2006,Drama,"In 1984 East Berlin, an agent of the secret po...",137
20,The Shining,8.4,4.2,Stanley Kubrick,Jack Nicholson Shelley Duvall Danny Lloyd,1980,Drama,A family heads to an isolated hotel for the wi...,146
21,Django Unchained,8.4,4.2,Quentin Tarantino,Jamie Foxx Christoph Waltz Leonardo DiCaprio,2012,Drama,"With the help of a German bounty hunter, a fre...",165
22,Whiplash,8.5,4.3,Damien Chazelle,Miles Teller J.K. Simmons Melissa Benoist,2014,Drama,A promising young drummer enrolls at a cut-thr...,106
23,The Departed,8.5,4.3,Martin Scorsese,Leonardo DiCaprio Matt Damon Jack Nicholson,2006,Crime,An undercover cop and a mole in the police att...,151
24,The Lion King,8.5,4.2,Roger Allers,Matthew Broderick Jeremy Irons James Earl Jones,1994,Animation,Lion prince Simba and his father are targeted ...,88
25,The Pianist,8.5,4.3,Roman Polanski,Adrien Brody Thomas Kretschmann Frank Finlay,2002,Biography,A Polish Jewish musician struggles to survive ...,150
26,The Green Mile,8.5,4.3,Frank Darabont,Tom Hanks Michael Clarke Duncan David Morse,1999,Crime,The lives of guards on Death Row are affected ...,189
27,Interstellar,8.6,4.3,Christopher Nolan,Matthew McConaughey Anne Hathaway Jessica Chas...,2014,Adventure,A team of explorers travel through a wormhole ...,169
28,Gladiator,8.5,4.3,Ridley Scott,Russell Crowe Joaquin Phoenix Connie Nielsen,2000,Action,A former Roman General sets out to exact venge...,155
29,American History X,8.5,4.2,Tony Kaye,Edward Norton Edward Furlong Beverly D'Angelo,1998,Drama,A former neo-nazi skinhead tries to prevent hi...,119
30,City of God,8.6,4.4,Fernando Meirelles,Alexandre Rodrigues Leandro Firmino Phellipe H...,2002,Crime,"In the slums of Rio, two kids' paths diverge a...",130
31,The Silence of the Lambs,8.6,4.4,Jonathan Demme,Jodie Foster Anthony Hopkins Lawrence A. Bonney,1991,Crime,A young F.B.I. cadet must receive the help of ...,118
32,It's a Wonderful Life,8.6,4.3,Frank Capra,James Stewart Donna Reed Lionel Barrymore,1946,Drama,An angel is sent from Heaven to help a despera...,130
33,Se7en,8.6,4.3,David Fincher,Morgan Freeman Brad Pitt Kevin Spacey,1995,Crime,"Two detectives, a rookie and a veteran, hunt a...",127
34,Life Is Beautiful,8.6,4.4,Roberto Benigni,Roberto Benigni Nicoletta Braschi Giorgio Cant...,1997,Comedy,When an open-minded Jewish librarian and his s...,116
35,The Usual Suspects,8.5,4.3,Bryan Singer,Kevin Spacey Gabriel Byrne Chazz Palminteri,1995,Crime,A sole survivor tells of the twisty events lea...,106
36,Leon: The Professional,8.5,4.3,Luc Besson,Jean Reno Gary Oldman Natalie Portman,1994,Crime,"Mathilda, a 12-year-old girl, is reluctantly t...",110
37,Spirited Away,8.5,4.4,Hayao Miyazaki,Daveigh Chase Suzanne Pleshette Miyu Irino,2001,Animation,"During her family's move to the suburbs, a sul...",125
38,Saving Private Ryan,8.5,4.3,Steven Spielberg,Tom Hanks Matt Damon Tom Sizemore,1998,Drama,"Following the Normandy Landings, a group of U....",169
39,The Departed,8.5,4.3,Martin Scorsese,Leonardo DiCaprio Matt Damon Jack Nicholson,2005,Thriller,An undercover agent and a spy constantly try t...,151
40,Spirited Away,8.6,4.5,Hayao Miyazaki,NaN,2001,Fantasy,Ten-year-old Chihiro and her parents end up at...,125

In [5]:
print("Attributes:",films.columns.tolist())

Attributes: ['Film Title', 'IMDb Rating', 'Letterboxd Rating', 'Director', 'Lead Cast', 'Year of Release', 'Genre', 'Plot', 'Runtime']

In [6]:
columns = ['Film Title','Director','Lead Cast','Genre','Plot']
films1 = films[columns]

In [7]:
films1.head()

,Film Title,Director,Lead Cast,Genre,Plot
0,The Shawshank Redemption,Frank Darabont,Tim Robbins Morgan Freeman Bob Gunton,Drama,Two imprisoned men bond over a number of years...
1,The Godfather,Francis Ford Coppola,Marlon Brando Al Pacino James Caan,Crime,The aging patriarch of an organized crime dyna...
2,The Godfather: Part II,Francis Ford Coppola,Al Pacino Robert De Niro Robert Duvall,Crime,The early life and career of Vito Corleone in ...
3,The Dark Knight,Christopher Nolan,Christian Bale Heath Ledger Aaron Eckhart,Action,When the menace known as The Joker wreaks havo...
4,12 Angry Men,Sidney Lumet,Henry Fonda Lee J. Cobb Martin Balsam,Drama,A jury holdout attempts to prevent a miscarria...

**Natural Language Processing**

In [8]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string

In [9]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [10]:
def preprocess_plot(plot):
    tokens = word_tokenize(plot.lower())

    table = str.maketrans('', '', string.punctuation)
    stripped = [w.translate(table) for w in tokens]

    stop_words = set(stopwords.words('english'))

    filtered_words = [word for word in stripped if word not in stop_words]

    filtered_plot = ' '.join(filtered_words)
    return filtered_plot

In [11]:
films1['Plot'] = films1['Plot'].apply(preprocess_plot)

<ipython-input-11-c4832c7dac02>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  films1['Plot'] = films1['Plot'].apply(preprocess_plot)

In [12]:
films1

,Film Title,Director,Lead Cast,Genre,Plot
0,The Shawshank Redemption,Frank Darabont,Tim Robbins Morgan Freeman Bob Gunton,Drama,two imprisoned men bond number years finding ...
1,The Godfather,Francis Ford Coppola,Marlon Brando Al Pacino James Caan,Crime,aging patriarch organized crime dynasty transf...
2,The Godfather: Part II,Francis Ford Coppola,Al Pacino Robert De Niro Robert Duvall,Crime,early life career vito corleone 1920s new york...
3,The Dark Knight,Christopher Nolan,Christian Bale Heath Ledger Aaron Eckhart,Action,menace known joker wreaks havoc chaos people g...
4,12 Angry Men,Sidney Lumet,Henry Fonda Lee J. Cobb Martin Balsam,Drama,jury holdout attempts prevent miscarriage just...
5,Schindler's List,Steven Spielberg,Liam Neeson Ralph Fiennes Ben Kingsley,Biography,germanoccupied poland world war ii industrial...
6,The Lord of the Rings: The Return of the King,Peter Jackson,Elijah Wood Viggo Mortensen Ian McKellen,Adventure,gandalf aragorn lead world men sauron army dra...
7,Pulp Fiction,Quentin Tarantino,John Travolta Uma Thurman Samuel L. Jackson,Crime,lives two mob hitmen boxer gangster wife pa...
8,Forrest Gump,Robert Zemeckis,Tom Hanks Robin Wright Gary Sinise,Drama,presidencies kennedy johnson vietnam war wat...
9,The Lord of the Rings: The Fellowship of the Ring,Peter Jackson,Elijah Wood Ian McKellen Orlando Bloom,Adventure,meek hobbit shire eight companions set journey...
10,Fight Club,David Fincher,Brad Pitt Edward Norton Meat Loaf,Drama,insomniac office worker devilmaycare soapmaker...
11,The Lord of the Rings: The Two Towers,Peter Jackson,Elijah Wood Ian McKellen Viggo Mortensen,Adventure,frodo sam edge closer mordor help shifty gollu...
12,Goodfellas,Martin Scorsese,Robert De Niro Ray Liotta Joe Pesci,Biography,story henry hill life mob covering relationsh...
13,The Matrix,Lana Wachowski Lilly Wachowski Keanu Reeves La...,Lana Wachowski Lilly Wachowski Keanu Reeves La...,Action,computer hacker learns mysterious rebels true ...
14,The Intouchables,Olivier Nakache Ã‰ric Toledano,FranÃ§ois Cluzet Omar Sy Anne Le Ny,Biography,becomes quadriplegic paragliding accident ari...
15,The Lion King,Roger Allers Rob Minkoff,Matthew Broderick Jeremy Irons James Earl Jones,Animation,lion prince simba father targeted bitter uncle...
16,Terminator 2: Judgment Day,James Cameron,Arnold Schwarzenegger Linda Hamilton Edward Fu...,Action,cyborg identical one failed kill sarah connor...
17,Back to the Future,Robert Zemeckis,Michael J. Fox Christopher Lloyd Lea Thompson,Adventure,marty mcfly 17yearold high school student ac...
18,The Prestige,Christopher Nolan,Christian Bale Hugh Jackman Scarlett Johansson,Drama,tragic accident two stage magicians engage ba...
19,The Lives of Others,Florian Henckel von Donnersmarck,Ulrich MÃ¼he Martina Gedeck Sebastian Koch,Drama,1984 east berlin agent secret police conduct...
20,The Shining,Stanley Kubrick,Jack Nicholson Shelley Duvall Danny Lloyd,Drama,family heads isolated hotel winter sinister pr...
21,Django Unchained,Quentin Tarantino,Jamie Foxx Christoph Waltz Leonardo DiCaprio,Drama,help german bounty hunter freed slave sets re...
22,Whiplash,Damien Chazelle,Miles Teller J.K. Simmons Melissa Benoist,Drama,promising young drummer enrolls cutthroat musi...
23,The Departed,Martin Scorsese,Leonardo DiCaprio Matt Damon Jack Nicholson,Crime,undercover cop mole police attempt identify in...
24,The Lion King,Roger Allers,Matthew Broderick Jeremy Irons James Earl Jones,Animation,lion prince simba father targeted bitter uncle...
25,The Pianist,Roman Polanski,Adrien Brody Thomas Kretschmann Frank Finlay,Biography,polish jewish musician struggles survive destr...
26,The Green Mile,Frank Darabont,Tom Hanks Michael Clarke Duncan David Morse,Crime,lives guards death row affected one charges b...
27,Interstellar,Christopher Nolan,Matthew McConaughey Anne Hathaway Jessica Chas...,Adventure,team explorers travel wormhole space attempt e...
28,Gladiator,Ridley Scott,Russell Crowe Joaquin Phoenix Connie Nielsen,Action,former roman general sets exact vengeance corr...
29,American History X,Tony Kaye,Edward Norton Edward Furlong Beverly D'Angelo,Drama,former neonazi skinhead tries prevent younger ...
30,City of God,Fernando Meirelles,Alexandre Rodrigues Leandro Firmino Phellipe H...,Crime,slums rio two kids paths diverge one struggl...
31,The Silence of the Lambs,Jonathan Demme,Jodie Foster Anthony Hopkins Lawrence A. Bonney,Crime,young fbi cadet must receive help incarcerate...
32,It's a Wonderful Life,Frank Capra,James Stewart Donna Reed Lionel Barrymore,Drama,angel sent heaven help desperately frustrated ...
33,Se7en,David Fincher,Morgan Freeman Brad Pitt Kevin Spacey,Crime,two detectives rookie veteran hunt serial ki...
34,Life Is Beautiful,Roberto Benigni,Roberto Benigni Nicoletta Braschi Giorgio Cant...,Comedy,openminded jewish librarian son become victims...
35,The Usual Suspects,Bryan Singer,Kevin Spacey Gabriel Byrne Chazz Palminteri,Crime,sole survivor tells twisty events leading horr...
36,Leon: The Professional,Luc Besson,Jean Reno Gary Oldman Natalie Portman,Crime,mathilda 12yearold girl reluctantly taken lÃ©...
37,Spirited Away,Hayao Miyazaki,Daveigh Chase Suzanne Pleshette Miyu Irino,Animation,family move suburbs sullen 10yearold girl wan...
38,Saving Private Ryan,Steven Spielberg,Tom Hanks Matt Damon Tom Sizemore,Drama,following normandy landings group us soldiers...
39,The Departed,Martin Scorsese,Leonardo DiCaprio Matt Damon Jack Nicholson,Thriller,undercover agent spy constantly try counteratt...
40,Spirited Away,Hayao Miyazaki,NaN,Fantasy,tenyearold chihiro parents end abandoned amuse...

In [13]:
columns1 = ['Film Title','Plot']
films2  = films1[columns1]
films2.tail()

                Film Title                                               Plot
36  Leon: The Professional  mathilda  12yearold girl  reluctantly taken lÃ©...
37           Spirited Away  family move suburbs  sullen 10yearold girl wan...
38     Saving Private Ryan  following normandy landings  group us soldiers...
39            The Departed  undercover agent spy constantly try counteratt...
40           Spirited Away  tenyearold chihiro parents end abandoned amuse...

**Feature Extraction**

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
tfidf_vectorizer = TfidfVectorizer(max_features=10)

tfidf_matrix = tfidf_vectorizer.fit_transform(films1['Plot'])

feature_names = tfidf_vectorizer.get_feature_names_out()

tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=feature_names)

for idx, row in tfidf_df.iterrows():
    print(f"{films1.at[idx, 'Film Title']}': {', '.join(tfidf_df.columns[row > 0])}")

The Shawshank Redemption': two
The Godfather': son
The Godfather: Part II': family, son
The Dark Knight': must, one
12 Angry Men':
Schindler's List': becomes, war, world
The Lord of the Rings: The Return of the King': one, sauron, world
Pulp Fiction': two
Forrest Gump': war
The Lord of the Rings: The Fellowship of the Ring': one, sauron
Fight Club':
The Lord of the Rings: The Two Towers': help, sauron
Goodfellas':
The Matrix': war
The Intouchables': becomes
The Lion King':
Terminator 2: Judgment Day': must, one, son
Back to the Future':
The Prestige': two
The Lives of Others':
The Shining': family, son
Django Unchained': help
Whiplash':
The Departed':
The Lion King':
The Pianist': war, world
The Green Mile': one
Interstellar':
Gladiator': family
American History X':
City of God': one, two
The Silence of the Lambs': help, must
It's a Wonderful Life': help
Se7en': two
Life Is Beautiful': son
The Usual Suspects':
Leon: The Professional': becomes, family
Spirited Away': family, world
Saving Private Ryan':
The Departed':
Spirited Away': must

In [16]:
tfidf_df

,becomes,family,help,must,one,sauron,son,two,war,world
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
2,0.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.707107,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.746092,0.665843,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.603843,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.563637,0.563637
6,0.000000,0.000000,0.000000,0.000000,0.520110,0.624368,0.000000,0.000000,0.000000,0.582796
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.640042,0.768340,0.000000,0.000000,0.000000,0.000000
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,0.000000,0.000000,0.682351,0.000000,0.000000,0.731025,0.000000,0.000000,0.000000,0.000000
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
14,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,0.000000,0.000000,0.000000,0.610474,0.544811,0.000000,0.574894,0.000000,0.000000,0.000000
17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,0.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.707107,0.000000,0.000000,0.000000
21,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.707107,0.707107
26,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
27,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
29,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30,0.000000,0.000000,0.000000,0.000000,0.687861,0.000000,0.000000,0.725842,0.000000,0.000000
31,0.000000,0.000000,0.894427,0.447214,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
32,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
33,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
34,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
35,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
36,0.751080,0.660211,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37,0.000000,0.685573,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.728003
38,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
39,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
40,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [17]:
genre_list = films1['Genre'].tolist()
genres = ",".join(str(gen) for gen in genre_list)
lead_cast = films1['Lead Cast'].tolist()
leads = ",".join(str(l) for l in lead_cast)
director = films1['Director'].tolist()

In [18]:
def join_names(names):
    if isinstance(names, str):
        split_names = names.split(', ')
        if len(split_names) == 2:
            first_name, last_name = split_names
            return f"{first_name} {last_name}"

**Bag of Words**

In [19]:
for index, row in films1.iterrows():
    words = ''
    for col in columns:
        words += ' '.join(str(row[col]).split()) + ' '
    films1.at[index, 'Bag_of_words'] = words.strip()

films1 = films1[['Film Title', 'Bag_of_words']]

<ipython-input-19-ed7de690dcb1>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  films1.at[index, 'Bag_of_words'] = words.strip()

In [20]:
films1

,Film Title,Bag_of_words
0,The Shawshank Redemption,The Shawshank Redemption Frank Darabont Tim Ro...
1,The Godfather,The Godfather Francis Ford Coppola Marlon Bran...
2,The Godfather: Part II,The Godfather: Part II Francis Ford Coppola Al...
3,The Dark Knight,The Dark Knight Christopher Nolan Christian Ba...
4,12 Angry Men,12 Angry Men Sidney Lumet Henry Fonda Lee J. C...
5,Schindler's List,Schindler's List Steven Spielberg Liam Neeson ...
6,The Lord of the Rings: The Return of the King,The Lord of the Rings: The Return of the King ...
7,Pulp Fiction,Pulp Fiction Quentin Tarantino John Travolta U...
8,Forrest Gump,Forrest Gump Robert Zemeckis Tom Hanks Robin W...
9,The Lord of the Rings: The Fellowship of the Ring,The Lord of the Rings: The Fellowship of the R...
10,Fight Club,Fight Club David Fincher Brad Pitt Edward Nort...
11,The Lord of the Rings: The Two Towers,The Lord of the Rings: The Two Towers Peter Ja...
12,Goodfellas,Goodfellas Martin Scorsese Robert De Niro Ray ...
13,The Matrix,The Matrix Lana Wachowski Lilly Wachowski Kean...
14,The Intouchables,The Intouchables Olivier Nakache Ã‰ric Toledano...
15,The Lion King,The Lion King Roger Allers Rob Minkoff Matthew...
16,Terminator 2: Judgment Day,Terminator 2: Judgment Day James Cameron Arnol...
17,Back to the Future,Back to the Future Robert Zemeckis Michael J. ...
18,The Prestige,The Prestige Christopher Nolan Christian Bale ...
19,The Lives of Others,The Lives of Others Florian Henckel von Donner...
20,The Shining,The Shining Stanley Kubrick Jack Nicholson She...
21,Django Unchained,Django Unchained Quentin Tarantino Jamie Foxx ...
22,Whiplash,Whiplash Damien Chazelle Miles Teller J.K. Sim...
23,The Departed,The Departed Martin Scorsese Leonardo DiCaprio...
24,The Lion King,The Lion King Roger Allers Matthew Broderick J...
25,The Pianist,The Pianist Roman Polanski Adrien Brody Thomas...
26,The Green Mile,The Green Mile Frank Darabont Tom Hanks Michae...
27,Interstellar,Interstellar Christopher Nolan Matthew McConau...
28,Gladiator,Gladiator Ridley Scott Russell Crowe Joaquin P...
29,American History X,American History X Tony Kaye Edward Norton Edw...
30,City of God,City of God Fernando Meirelles Alexandre Rodri...
31,The Silence of the Lambs,The Silence of the Lambs Jonathan Demme Jodie ...
32,It's a Wonderful Life,It's a Wonderful Life Frank Capra James Stewar...
33,Se7en,Se7en David Fincher Morgan Freeman Brad Pitt K...
34,Life Is Beautiful,Life Is Beautiful Roberto Benigni Roberto Beni...
35,The Usual Suspects,The Usual Suspects Bryan Singer Kevin Spacey G...
36,Leon: The Professional,Leon: The Professional Luc Besson Jean Reno Ga...
37,Spirited Away,Spirited Away Hayao Miyazaki Daveigh Chase Suz...
38,Saving Private Ryan,Saving Private Ryan Steven Spielberg Tom Hanks...
39,The Departed,The Departed Martin Scorsese Leonardo DiCaprio...
40,Spirited Away,Spirited Away Hayao Miyazaki nan Fantasy tenye...

In [21]:
bag_of_words = films1['Bag_of_words'].tolist()
bag_of_words

['The Shawshank Redemption Frank Darabont Tim Robbins Morgan Freeman Bob Gunton Drama two imprisoned men bond number years finding solace eventual redemption acts common decency',
 'The Godfather Francis Ford Coppola Marlon Brando Al Pacino James Caan Crime aging patriarch organized crime dynasty transfers control clandestine empire reluctant son',
 'The Godfather: Part II Francis Ford Coppola Al Pacino Robert De Niro Robert Duvall Crime early life career vito corleone 1920s new york city portrayed son michael expands tightens grip family crime syndicate',
 'The Dark Knight Christopher Nolan Christian Bale Heath Ledger Aaron Eckhart Action menace known joker wreaks havoc chaos people gotham batman must accept one greatest psychological physical tests ability fight injustice',
 '12 Angry Men Sidney Lumet Henry Fonda Lee J. Cobb Martin Balsam Drama jury holdout attempts prevent miscarriage justice forcing colleagues reconsider evidence',
 "Schindler's List Steven Spielberg Liam Neeson Ralph Fiennes Ben Kingsley Biography germanoccupied poland world war ii industrialist oskar schindler gradually becomes concerned jewish workforce witnessing persecution nazis",
 'The Lord of the Rings: The Return of the King Peter Jackson Elijah Wood Viggo Mortensen Ian McKellen Adventure gandalf aragorn lead world men sauron army draw gaze frodo sam approach mount doom one ring',
 'Pulp Fiction Quentin Tarantino John Travolta Uma Thurman Samuel L. Jackson Crime lives two mob hitmen boxer gangster wife pair diner bandits intertwine four tales violence redemption',
 'Forrest Gump Robert Zemeckis Tom Hanks Robin Wright Gary Sinise Drama presidencies kennedy johnson vietnam war watergate scandal historical events unfold perspective alabama man iq 75 whose desire reunited childhood sweetheart',
 'The Lord of the Rings: The Fellowship of the Ring Peter Jackson Elijah Wood Ian McKellen Orlando Bloom Adventure meek hobbit shire eight companions set journey destroy powerful one ring save middleearth dark lord sauron',
 'Fight Club David Fincher Brad Pitt Edward Norton Meat Loaf Drama insomniac office worker devilmaycare soapmaker form underground fight club evolves something much much',
 'The Lord of the Rings: The Two Towers Peter Jackson Elijah Wood Ian McKellen Viggo Mortensen Adventure frodo sam edge closer mordor help shifty gollum divided fellowship makes stand sauron new ally saruman hordes isengard',
 'Goodfellas Martin Scorsese Robert De Niro Ray Liotta Joe Pesci Biography story henry hill life mob covering relationship wife karen hill mob partners jimmy conway tommy devito italianamerican crime syndicate',
 'The Matrix Lana Wachowski Lilly Wachowski Keanu Reeves Laurence Fishburne Lana Wachowski Lilly Wachowski Keanu Reeves Laurence Fishburne Action computer hacker learns mysterious rebels true nature reality role war controllers',
 'The Intouchables Olivier Nakache Ã‰ric Toledano FranÃ§ois Cluzet Omar Sy Anne Le Ny Biography becomes quadriplegic paragliding accident aristocrat hires young man projects caregiver',
 'The Lion King Roger Allers Rob Minkoff Matthew Broderick Jeremy Irons James Earl Jones Animation lion prince simba father targeted bitter uncle wants ascend throne',
 'Terminator 2: Judgment Day James Cameron Arnold Schwarzenegger Linda Hamilton Edward Furlong Action cyborg identical one failed kill sarah connor must protect teenage son john connor advanced powerful cyborg',
 'Back to the Future Robert Zemeckis Michael J. Fox Christopher Lloyd Lea Thompson Adventure marty mcfly 17yearold high school student accidentally sent thirty years past timetraveling delorean invented close friend eccentric scientist doc brown',
 'The Prestige Christopher Nolan Christian Bale Hugh Jackman Scarlett Johansson Drama tragic accident two stage magicians engage battle create ultimate illusion sacrificing everything outwit',
 'The Lives of Others Florian Henckel von Donnersmarck Ulrich MÃ¼he Martina Gedeck Sebastian Koch Drama 1984 east berlin agent secret police conducting surveillance writer lover finds becoming increasingly absorbed lives',
 'The Shining Stanley Kubrick Jack Nicholson Shelley Duvall Danny Lloyd Drama family heads isolated hotel winter sinister presence influences father violence psychic son sees horrific forebodings past future',
 'Django Unchained Quentin Tarantino Jamie Foxx Christoph Waltz Leonardo DiCaprio Drama help german bounty hunter freed slave sets rescue wife brutal mississippi plantation owner',
 'Whiplash Damien Chazelle Miles Teller J.K. Simmons Melissa Benoist Drama promising young drummer enrolls cutthroat music conservatory dreams greatness mentored instructor stop nothing realize student potential',
 'The Departed Martin Scorsese Leonardo DiCaprio Matt Damon Jack Nicholson Crime undercover cop mole police attempt identify infiltrating irish gang south boston',
 'The Lion King Roger Allers Matthew Broderick Jeremy Irons James Earl Jones Animation lion prince simba father targeted bitter uncle wants ascend throne',
 'The Pianist Roman Polanski Adrien Brody Thomas Kretschmann Frank Finlay Biography polish jewish musician struggles survive destruction warsaw ghetto world war ii',
 'The Green Mile Frank Darabont Tom Hanks Michael Clarke Duncan David Morse Crime lives guards death row affected one charges black man accused child murder rape yet mysterious gift',
 'Interstellar Christopher Nolan Matthew McConaughey Anne Hathaway Jessica Chastain Adventure team explorers travel wormhole space attempt ensure humanity survival',
 'Gladiator Ridley Scott Russell Crowe Joaquin Phoenix Connie Nielsen Action former roman general sets exact vengeance corrupt emperor murdered family sent slavery',
 "American History X Tony Kaye Edward Norton Edward Furlong Beverly D'Angelo Drama former neonazi skinhead tries prevent younger brother going wrong path",
 'City of God Fernando Meirelles Alexandre Rodrigues Leandro Firmino Phellipe Haagensen Crime slums rio two kids paths diverge one struggles become photographer kingpin',
 'The Silence of the Lambs Jonathan Demme Jodie Foster Anthony Hopkins Lawrence A. Bonney Crime young fbi cadet must receive help incarcerated manipulative cannibal killer help catch another serial killer madman skins victims',
 "It's a Wonderful Life Frank Capra James Stewart Donna Reed Lionel Barrymore Drama angel sent heaven help desperately frustrated businessman showing life would like never existed",
 'Se7en David Fincher Morgan Freeman Brad Pitt Kevin Spacey Crime two detectives rookie veteran hunt serial killer uses seven deadly sins motives',
 'Life Is Beautiful Roberto Benigni Roberto Benigni Nicoletta Braschi Giorgio Cantarini Comedy openminded jewish librarian son become victims holocaust uses perfect mixture humor imagination protect son dangers around camp',
 'The Usual Suspects Bryan Singer Kevin Spacey Gabriel Byrne Chazz Palminteri Crime sole survivor tells twisty events leading horrific gun battle boat began five criminals met seemingly random police lineup',
 'Leon: The Professional Luc Besson Jean Reno Gary Oldman Natalie Portman Crime mathilda 12yearold girl reluctantly taken lÃ©on professional assassin family murdered unusual relationship forms becomes protÃ©gÃ©e learns assassin trade',
 'Spirited Away Hayao Miyazaki Daveigh Chase Suzanne Pleshette Miyu Irino Animation family move suburbs sullen 10yearold girl wanders world ruled gods witches spirits humans changed beasts',
 'Saving Private Ryan Steven Spielberg Tom Hanks Matt Damon Tom Sizemore Drama following normandy landings group us soldiers go behind enemy lines retrieve paratrooper whose brothers killed action',
 'The Departed Martin Scorsese Leonardo DiCaprio Matt Damon Jack Nicholson Thriller undercover agent spy constantly try counterattack order save exposed front authorities meanwhile try infiltrate irish gang',
 'Spirited Away Hayao Miyazaki nan Fantasy tenyearold chihiro parents end abandoned amusement park inhabited supernatural beings soon learns must work free parents turned pigs']

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
count = CountVectorizer()
count_matrix = count.fit_transform(films1['Bag_of_words'])
count_matrix
cosine_sim = cosine_similarity(count_matrix, count_matrix)
print(cosine_sim)

[[1.         0.03849002 0.0316386  ... 0.03513642 0.03573708 0.        ]
 [0.03849002 1.         0.39455757 ... 0.         0.03713907 0.        ]
 [0.0316386  0.39455757 1.         ... 0.         0.03052813 0.        ]
 ...
 [0.03513642 0.         0.         ... 1.         0.06780635 0.        ]
 [0.03573708 0.03713907 0.03052813 ... 0.06780635 1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]

In [24]:
indices = pd.Series(films1['Film Title'])
indices

0                              The Shawshank Redemption
1                                         The Godfather
2                                The Godfather: Part II
3                                       The Dark Knight
4                                          12 Angry Men
5                                      Schindler's List
6         The Lord of the Rings: The Return of the King
7                                          Pulp Fiction
8                                          Forrest Gump
9     The Lord of the Rings: The Fellowship of the Ring
10                                           Fight Club
11                The Lord of the Rings: The Two Towers
12                                           Goodfellas
13                                           The Matrix
14                                     The Intouchables
15                                        The Lion King
16                           Terminator 2: Judgment Day
17                                   Back to the Future
18                                         The Prestige
19                                  The Lives of Others
20                                          The Shining
21                                     Django Unchained
22                                             Whiplash
23                                         The Departed
24                                        The Lion King
25                                          The Pianist
26                                       The Green Mile
27                                         Interstellar
28                                            Gladiator
29                                   American History X
30                                          City of God
31                             The Silence of the Lambs
32                                It's a Wonderful Life
33                                                Se7en
34                                    Life Is Beautiful
35                                   The Usual Suspects
36                               Leon: The Professional
37                                        Spirited Away
38                                  Saving Private Ryan
39                                         The Departed
40                                        Spirited Away
Name: Film Title, dtype: object

**Function for Movie Recommendation**

In [26]:
def recommend(title, cosine_sim = cosine_sim):
    recommended_movies = []
    idx = indices[indices == title].index[0]
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)
    top_5_indices = list(score_series.iloc[1:6].index)

    for i in top_5_indices:
        recommended_movies.append(list(films1['Film Title'])[i])

    return recommended_movies

recommend('The Lord of the Rings: The Fellowship of the Ring')

['The Lord of the Rings: The Return of the King',
 'The Lord of the Rings: The Two Towers',
 'The Silence of the Lambs',
 'The Dark Knight',
 'The Lives of Others']